/*******************************************************************************
 * Copyright 2011-2013 Sergey Tarasevich
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package jp.ne.jyuujitunohyojyunsiyou.untils;

import jp.ne.jyuujitunohyojyunsiyou.R;

/**
 * @author Sergey Tarasevich (nostra13[at]gmail[dot]com)
 */
public final class Constants {

	public static final String[] IMAGES = new String[] {
			// Heavy images
			"drawable://" + R.drawable.dummy_smart_page11_background,
			"drawable://" + R.drawable.dummy_smart_page15_background,
			"drawable://" + R.drawable.dummy_smart_page4_background,
			"drawable://" + R.drawable.dummy_smart_page6_background,
			"drawable://" + R.drawable.dummy_smart_page8_background,
			"drawable://" + R.drawable.page10_main_1,
			"drawable://" + R.drawable.page10_main_2,
			"drawable://" + R.drawable.page10_main_3,
			"drawable://" + R.drawable.page10_main_4,
			"drawable://" + R.drawable.page10_main_5,
			"drawable://" + R.drawable.page11_main,
			"drawable://" + R.drawable.page13_main,
			"drawable://" + R.drawable.page16_main,
			"drawable://" + R.drawable.page16_main15,
			"drawable://" + R.drawable.page16_main16,
			"drawable://" + R.drawable.page7_main,
			"drawable://" + R.drawable.page8_popup1,
			"drawable://" + R.drawable.page8_popup2,
			"drawable://" + R.drawable.page8_popup3,
			"drawable://" + R.drawable.page12_main,
			"drawable://" + R.drawable.page14_main,
			"drawable://" + R.drawable.page14_sw1_main1,
			"drawable://" + R.drawable.page18_main2,
			"drawable://" + R.drawable.page18_sw1_main1,
			"drawable://" + R.drawable.page18_sw1_main2,
			"drawable://" + R.drawable.page18_sw1_main3,
			"drawable://" + R.drawable.page18_sw1_main4,
			"drawable://" + R.drawable.page18_sw2_main2,
			"drawable://" + R.drawable.page18_sw2_main3,
			"drawable://" + R.drawable.page18_sw2_main4,
			"drawable://" + R.drawable.page18_sw3_main1,
			"drawable://" + R.drawable.page18_sw3_main2,
			"drawable://" + R.drawable.page18_sw3_main3,
			"drawable://" + R.drawable.page18_sw3_main4,
			"drawable://" + R.drawable.page18_sw4_main1,
			"drawable://" + R.drawable.page18_sw4_main2,
			"drawable://" + R.drawable.dummy_smart_page11_background,
			"drawable://" + R.drawable.dummy_smart_page15_background,
			"drawable://" + R.drawable.dummy_smart_page4_background,
			"drawable://" + R.drawable.dummy_smart_page6_background,
			"drawable://" + R.drawable.dummy_smart_page8_background,
			"drawable://" + R.drawable.page10_main_1,
			"drawable://" + R.drawable.page10_main_2,
			"drawable://" + R.drawable.page10_main_3,
			"drawable://" + R.drawable.page10_main_4,
			"drawable://" + R.drawable.page10_main_5,
			"drawable://" + R.drawable.page11_main,
			"drawable://" + R.drawable.page13_main,
			"drawable://" + R.drawable.page16_main,
			"drawable://" + R.drawable.page16_main15,
			"drawable://" + R.drawable.page16_main16,
			"drawable://" + R.drawable.page7_main,
			"drawable://" + R.drawable.page8_popup1,
			"drawable://" + R.drawable.page8_popup2,
			"drawable://" + R.drawable.page8_popup3,
			"drawable://" + R.drawable.page12_main,
			"drawable://" + R.drawable.page14_main,
			"drawable://" + R.drawable.page14_sw1_main1,
			"drawable://" + R.drawable.page18_main2,
			"drawable://" + R.drawable.page18_sw1_main1,
			"drawable://" + R.drawable.page18_sw1_main2,
			"drawable://" + R.drawable.page18_sw1_main3,
			"drawable://" + R.drawable.page18_sw1_main4,
			"drawable://" + R.drawable.page18_sw2_main2,
			"drawable://" + R.drawable.page18_sw2_main3,
			"drawable://" + R.drawable.page18_sw2_main4,
			"drawable://" + R.drawable.page18_sw3_main1,
			"drawable://" + R.drawable.page18_sw3_main2,
			"drawable://" + R.drawable.page18_sw3_main3,
			"drawable://" + R.drawable.page18_sw3_main4,
			"drawable://" + R.drawable.page18_sw4_main1,
			"drawable://" + R.drawable.page18_sw4_main2,
			"drawable://" + R.drawable.dummy_smart_page11_background,
			"drawable://" + R.drawable.dummy_smart_page15_background,
			"drawable://" + R.drawable.dummy_smart_page4_background,
			"drawable://" + R.drawable.dummy_smart_page6_background,
			"drawable://" + R.drawable.dummy_smart_page8_background,
			"drawable://" + R.drawable.page10_main_1,
			"drawable://" + R.drawable.page10_main_2,
			"drawable://" + R.drawable.page10_main_3,
			"drawable://" + R.drawable.page10_main_4,
			"drawable://" + R.drawable.page10_main_5,
			"drawable://" + R.drawable.page11_main,
			"drawable://" + R.drawable.page13_main,
			"drawable://" + R.drawable.page16_main,
			"drawable://" + R.drawable.page16_main15,
			"drawable://" + R.drawable.page16_main16,
			"drawable://" + R.drawable.page7_main,
			"drawable://" + R.drawable.page8_popup1,
			"drawable://" + R.drawable.page8_popup2,
			"drawable://" + R.drawable.page8_popup3,
			"drawable://" + R.drawable.page12_main,
			"drawable://" + R.drawable.page14_main,
			"drawable://" + R.drawable.page14_sw1_main1,
			"drawable://" + R.drawable.page18_main2,
			"drawable://" + R.drawable.page18_sw1_main1,
			"drawable://" + R.drawable.page18_sw1_main2,
			"drawable://" + R.drawable.page18_sw1_main3,
			"drawable://" + R.drawable.page18_sw1_main4,
			"drawable://" + R.drawable.page18_sw2_main2,
			"drawable://" + R.drawable.page18_sw2_main3,
			"drawable://" + R.drawable.page18_sw2_main4,
			"drawable://" + R.drawable.page18_sw3_main1,
			"drawable://" + R.drawable.page18_sw3_main2,
			"drawable://" + R.drawable.page18_sw3_main3,
			"drawable://" + R.drawable.page18_sw3_main4,
			"drawable://" + R.drawable.page18_sw4_main1,
			"drawable://" + R.drawable.page18_sw4_main2,
			"drawable://" + R.drawable.dummy_smart_page11_background,
			"drawable://" + R.drawable.dummy_smart_page15_background,
			"drawable://" + R.drawable.dummy_smart_page4_background,
			"drawable://" + R.drawable.dummy_smart_page6_background,
			"drawable://" + R.drawable.dummy_smart_page8_background,
			"drawable://" + R.drawable.page10_main_1,
			"drawable://" + R.drawable.page10_main_2,
			"drawable://" + R.drawable.page10_main_3,
			"drawable://" + R.drawable.page10_main_4,
			"drawable://" + R.drawable.page10_main_5,
			"drawable://" + R.drawable.page11_main,
			"drawable://" + R.drawable.page13_main,
			"drawable://" + R.drawable.page16_main,
			"drawable://" + R.drawable.page16_main15,
			"drawable://" + R.drawable.page16_main16,
			"drawable://" + R.drawable.page7_main,
			"drawable://" + R.drawable.page8_popup1,
			"drawable://" + R.drawable.page8_popup2,
			"drawable://" + R.drawable.page8_popup3,
			"drawable://" + R.drawable.page12_main,
			"drawable://" + R.drawable.page14_main,
			"drawable://" + R.drawable.page14_sw1_main1,
			"drawable://" + R.drawable.page18_main2,
			"drawable://" + R.drawable.page18_sw1_main1,
			"drawable://" + R.drawable.page18_sw1_main2,
			"drawable://" + R.drawable.page18_sw1_main3,
			"drawable://" + R.drawable.page18_sw1_main4,
			"drawable://" + R.drawable.page18_sw2_main2,
			"drawable://" + R.drawable.page18_sw2_main3,
			"drawable://" + R.drawable.page18_sw2_main4,
			"drawable://" + R.drawable.page18_sw3_main1,
			"drawable://" + R.drawable.page18_sw3_main2,
			"drawable://" + R.drawable.page18_sw3_main3,
			"drawable://" + R.drawable.page18_sw3_main4,
			"drawable://" + R.drawable.page18_sw4_main1,
			"drawable://" + R.drawable.page18_sw4_main2,
			"drawable://" + R.drawable.dummy_smart_page11_background,
			"drawable://" + R.drawable.dummy_smart_page15_background,
			"drawable://" + R.drawable.dummy_smart_page4_background,
			"drawable://" + R.drawable.dummy_smart_page6_background,
			"drawable://" + R.drawable.dummy_smart_page8_background,
			"drawable://" + R.drawable.page10_main_1,
			"drawable://" + R.drawable.page10_main_2,
			"drawable://" + R.drawable.page10_main_3,
			"drawable://" + R.drawable.page10_main_4,
			"drawable://" + R.drawable.page10_main_5,
			"drawable://" + R.drawable.page11_main,
			"drawable://" + R.drawable.page13_main,
			"drawable://" + R.drawable.page16_main,
			"drawable://" + R.drawable.page16_main15,
			"drawable://" + R.drawable.page16_main16,
			"drawable://" + R.drawable.page7_main,
			"drawable://" + R.drawable.page8_popup1,
			"drawable://" + R.drawable.page8_popup2,
			"drawable://" + R.drawable.page8_popup3,
			"drawable://" + R.drawable.page12_main,
			"drawable://" + R.drawable.page14_main,
			"drawable://" + R.drawable.page14_sw1_main1,
			"drawable://" + R.drawable.page18_main2,
			"drawable://" + R.drawable.page18_sw1_main1,
			"drawable://" + R.drawable.page18_sw1_main2,
			"drawable://" + R.drawable.page18_sw1_main3,
			"drawable://" + R.drawable.page18_sw1_main4,
			"drawable://" + R.drawable.page18_sw2_main2,
			"drawable://" + R.drawable.page18_sw2_main3,
			"drawable://" + R.drawable.page18_sw2_main4,
			"drawable://" + R.drawable.page18_sw3_main1,
			"drawable://" + R.drawable.page18_sw3_main2,
			"drawable://" + R.drawable.page18_sw3_main3,
			"drawable://" + R.drawable.page18_sw3_main4,
			"drawable://" + R.drawable.page18_sw4_main1,
			"drawable://" + R.drawable.page18_sw4_main2,
			
	};

	public static final Integer[] IMAGES_THUMPS = new Integer[] {
		// Heavy images
		R.drawable.dummy_smart_page11_background_thumps,
		R.drawable.dummy_smart_page15_background_thumps,
		R.drawable.dummy_smart_page4_background_thumps,
		R.drawable.dummy_smart_page6_background_thumps,
		R.drawable.dummy_smart_page8_background_thumps,
		R.drawable.page10_main_1_thumps,
		R.drawable.page10_main_2_thumps,
		R.drawable.page10_main_3_thumps,
		R.drawable.page10_main_4_thumps,
		R.drawable.page10_main_5_thumps,
		R.drawable.page11_main_thumps,
		R.drawable.page13_main_thumps,
		R.drawable.page16_main_thumps,
		R.drawable.page16_main15_thumps,
		R.drawable.page16_main16_thumps,
		R.drawable.page7_main_thumps,
		R.drawable.page8_popup1_thumps,
		R.drawable.page8_popup2_thumps,
		R.drawable.page8_popup3_thumps,
		R.drawable.page12_main_thumb,
		R.drawable.page14_main_thumb,
		R.drawable.page14_sw1_main1_thumb,
		R.drawable.page18_main2_thumb,
		R.drawable.page18_sw1_main1_thumb,
		R.drawable.page18_sw1_main2_thumb,
		R.drawable.page18_sw1_main3_thumb,
		R.drawable.page18_sw1_main4_thumb,
		R.drawable.page18_sw2_main2_thumb,
		R.drawable.page18_sw2_main3_thumb,
		R.drawable.page18_sw2_main4_thumb,
		R.drawable.page18_sw3_main1_thumb,
		R.drawable.page18_sw3_main2_thumb,
		R.drawable.page18_sw3_main3_thumb,
		R.drawable.page18_sw3_main4_thumb,
		R.drawable.page18_sw4_main1_thumb,
		R.drawable.page18_sw4_main2_thumb,
		R.drawable.dummy_smart_page11_background_thumps,
		R.drawable.dummy_smart_page15_background_thumps,
		R.drawable.dummy_smart_page4_background_thumps,
		R.drawable.dummy_smart_page6_background_thumps,
		R.drawable.dummy_smart_page8_background_thumps,
		R.drawable.page10_main_1_thumps,
		R.drawable.page10_main_2_thumps,
		R.drawable.page10_main_3_thumps,
		R.drawable.page10_main_4_thumps,
		R.drawable.page10_main_5_thumps,
		R.drawable.page11_main_thumps,
		R.drawable.page13_main_thumps,
		R.drawable.page16_main_thumps,
		R.drawable.page16_main15_thumps,
		R.drawable.page16_main16_thumps,
		R.drawable.page7_main_thumps,
		R.drawable.page8_popup1_thumps,
		R.drawable.page8_popup2_thumps,
		R.drawable.page8_popup3_thumps,
		R.drawable.page12_main_thumb,
		R.drawable.page14_main_thumb,
		R.drawable.page14_sw1_main1_thumb,
		R.drawable.page18_main2_thumb,
		R.drawable.page18_sw1_main1_thumb,
		R.drawable.page18_sw1_main2_thumb,
		R.drawable.page18_sw1_main3_thumb,
		R.drawable.page18_sw1_main4_thumb,
		R.drawable.page18_sw2_main2_thumb,
		R.drawable.page18_sw2_main3_thumb,
		R.drawable.page18_sw2_main4_thumb,
		R.drawable.page18_sw3_main1_thumb,
		R.drawable.page18_sw3_main2_thumb,
		R.drawable.page18_sw3_main3_thumb,
		R.drawable.page18_sw3_main4_thumb,
		R.drawable.page18_sw4_main1_thumb,
		R.drawable.page18_sw4_main2_thumb,
		R.drawable.dummy_smart_page11_background_thumps,
		R.drawable.dummy_smart_page15_background_thumps,
		R.drawable.dummy_smart_page4_background_thumps,
		R.drawable.dummy_smart_page6_background_thumps,
		R.drawable.dummy_smart_page8_background_thumps,
		R.drawable.page10_main_1_thumps,
		R.drawable.page10_main_2_thumps,
		R.drawable.page10_main_3_thumps,
		R.drawable.page10_main_4_thumps,
		R.drawable.page10_main_5_thumps,
		R.drawable.page11_main_thumps,
		R.drawable.page13_main_thumps,
		R.drawable.page16_main_thumps,
		R.drawable.page16_main15_thumps,
		R.drawable.page16_main16_thumps,
		R.drawable.page7_main_thumps,
		R.drawable.page8_popup1_thumps,
		R.drawable.page8_popup2_thumps,
		R.drawable.page8_popup3_thumps,
		R.drawable.page12_main_thumb,
		R.drawable.page14_main_thumb,
		R.drawable.page14_sw1_main1_thumb,
		R.drawable.page18_main2_thumb,
		R.drawable.page18_sw1_main1_thumb,
		R.drawable.page18_sw1_main2_thumb,
		R.drawable.page18_sw1_main3_thumb,
		R.drawable.page18_sw1_main4_thumb,
		R.drawable.page18_sw2_main2_thumb,
		R.drawable.page18_sw2_main3_thumb,
		R.drawable.page18_sw2_main4_thumb,
		R.drawable.page18_sw3_main1_thumb,
		R.drawable.page18_sw3_main2_thumb,
		R.drawable.page18_sw3_main3_thumb,
		R.drawable.page18_sw3_main4_thumb,
		R.drawable.page18_sw4_main1_thumb,
		R.drawable.page18_sw4_main2_thumb,
		R.drawable.dummy_smart_page11_background_thumps,
		R.drawable.dummy_smart_page15_background_thumps,
		R.drawable.dummy_smart_page4_background_thumps,
		R.drawable.dummy_smart_page6_background_thumps,
		R.drawable.dummy_smart_page8_background_thumps,
		R.drawable.page10_main_1_thumps,
		R.drawable.page10_main_2_thumps,
		R.drawable.page10_main_3_thumps,
		R.drawable.page10_main_4_thumps,
		R.drawable.page10_main_5_thumps,
		R.drawable.page11_main_thumps,
		R.drawable.page13_main_thumps,
		R.drawable.page16_main_thumps,
		R.drawable.page16_main15_thumps,
		R.drawable.page16_main16_thumps,
		R.drawable.page7_main_thumps,
		R.drawable.page8_popup1_thumps,
		R.drawable.page8_popup2_thumps,
		R.drawable.page8_popup3_thumps,
		R.drawable.page12_main_thumb,
		R.drawable.page14_main_thumb,
		R.drawable.page14_sw1_main1_thumb,
		R.drawable.page18_main2_thumb,
		R.drawable.page18_sw1_main1_thumb,
		R.drawable.page18_sw1_main2_thumb,
		R.drawable.page18_sw1_main3_thumb,
		R.drawable.page18_sw1_main4_thumb,
		R.drawable.page18_sw2_main2_thumb,
		R.drawable.page18_sw2_main3_thumb,
		R.drawable.page18_sw2_main4_thumb,
		R.drawable.page18_sw3_main1_thumb,
		R.drawable.page18_sw3_main2_thumb,
		R.drawable.page18_sw3_main3_thumb,
		R.drawable.page18_sw3_main4_thumb,
		R.drawable.page18_sw4_main1_thumb,
		R.drawable.page18_sw4_main2_thumb,
		R.drawable.dummy_smart_page11_background_thumps,
		R.drawable.dummy_smart_page15_background_thumps,
		R.drawable.dummy_smart_page4_background_thumps,
		R.drawable.dummy_smart_page6_background_thumps,
		R.drawable.dummy_smart_page8_background_thumps,
		R.drawable.page10_main_1_thumps,
		R.drawable.page10_main_2_thumps,
		R.drawable.page10_main_3_thumps,
		R.drawable.page10_main_4_thumps,
		R.drawable.page10_main_5_thumps,
		R.drawable.page11_main_thumps,
		R.drawable.page13_main_thumps,
		R.drawable.page16_main_thumps,
		R.drawable.page16_main15_thumps,
		R.drawable.page16_main16_thumps,
		R.drawable.page7_main_thumps,
		R.drawable.page8_popup1_thumps,
		R.drawable.page8_popup2_thumps,
		R.drawable.page8_popup3_thumps,
		R.drawable.page12_main_thumb,
		R.drawable.page14_main_thumb,
		R.drawable.page14_sw1_main1_thumb,
		R.drawable.page18_main2_thumb,
		R.drawable.page18_sw1_main1_thumb,
		R.drawable.page18_sw1_main2_thumb,
		R.drawable.page18_sw1_main3_thumb,
		R.drawable.page18_sw1_main4_thumb,
		R.drawable.page18_sw2_main2_thumb,
		R.drawable.page18_sw2_main3_thumb,
		R.drawable.page18_sw2_main4_thumb,
		R.drawable.page18_sw3_main1_thumb,
		R.drawable.page18_sw3_main2_thumb,
		R.drawable.page18_sw3_main3_thumb,
		R.drawable.page18_sw3_main4_thumb,
		R.drawable.page18_sw4_main1_thumb,
		R.drawable.page18_sw4_main2_thumb,
};
	
	private Constants() {
	}

	public static class Config {
		public static final boolean DEVELOPER_MODE = false;
	}

	public static class Extra {
		public static final String IMAGES = "com.nostra13.example.universalimageloader.IMAGES";
		public static final String IMAGE_POSITION = "com.nostra13.example.universalimageloader.IMAGE_POSITION";
	}
}
