
package jp.ne.jyuujitunohyojyunsiyou.untils;

import jp.ne.jyuujitunohyojyunsiyou.R;

public final class Constants {

	public static final String[] IMAGES = new String[] {
			// Heavy images
			"drawable://" + R.drawable.comfortable_bathroom_main01,
			"drawable://" + R.drawable.comfortable_bathroom_main02,
			"drawable://" + R.drawable.comfortable_bathroom_main03,
			"drawable://" + R.drawable.comfortable_bathroom_main04,
			"drawable://" + R.drawable.comfortable_bathroom_main05,
			"drawable://" + R.drawable.comfortable_bathroom_main06,
			"drawable://" + R.drawable.comfortable_bathroom_main07,
			"drawable://" + R.drawable.comfortable_bathroom_main08,
			"drawable://" + R.drawable.comfortable_bathroom_main09,
			"drawable://" + R.drawable.comfortable_bathroom_main10,
			"drawable://" + R.drawable.comfortable_bathroom_main11,
			"drawable://" + R.drawable.comfortable_bathroom_main12,
			"drawable://" + R.drawable.comfortable_bathroom_main13,
			"drawable://" + R.drawable.comfortable_bathroom_main14,
			"drawable://" + R.drawable.comfortable_bathroom_main15,
			"drawable://" + R.drawable.comfortable_bathroom_main16,
			"drawable://" + R.drawable.comfortable_bathroom_main17,
			"drawable://" + R.drawable.comfortable_bathroom_main18,
			"drawable://" + R.drawable.comfortable_bathroom_main19,
			"drawable://" + R.drawable.comfortable_bathroom_main20,
			"drawable://" + R.drawable.comfortable_bathroom_main21,
			"drawable://" + R.drawable.comfortable_bathroom_main22,
			"drawable://" + R.drawable.comfortable_bathroom_main23,
			"drawable://" + R.drawable.comfortable_bathroom_main24,
			"drawable://" + R.drawable.comfortable_bathroom_main25,
			"drawable://" + R.drawable.comfortable_bathroom_main26,
			"drawable://" + R.drawable.comfortable_bathroom_main27,
			"drawable://" + R.drawable.comfortable_bathroom_main28,
			"drawable://" + R.drawable.comfortable_bathroom_main29,
			"drawable://" + R.drawable.comfortable_bathroom_main30,
			"drawable://" + R.drawable.comfortable_bathroom_main31,
			"drawable://" + R.drawable.comfortable_bathroom_main32,
			"drawable://" + R.drawable.comfortable_bathroom_main33,
			"drawable://" + R.drawable.comfortable_bathroom_main32,
			"drawable://" + R.drawable.comfortable_bathroom_main33,
			"drawable://" + R.drawable.comfortable_bathroom_main34,
			"drawable://" + R.drawable.comfortable_bathroom_main35,
			"drawable://" + R.drawable.comfortable_bathroom_main36,
			"drawable://" + R.drawable.comfortable_bathroom_main37,
			"drawable://" + R.drawable.comfortable_bathroom_main38,
			"drawable://" + R.drawable.comfortable_bathroom_main39,
			"drawable://" + R.drawable.comfortable_bathroom_main40,
			"drawable://" + R.drawable.comfortable_kitchen_main01,
			"drawable://" + R.drawable.comfortable_kitchen_main02,
			"drawable://" + R.drawable.comfortable_kitchen_main03,
			"drawable://" + R.drawable.comfortable_kitchen_main04,
			"drawable://" + R.drawable.comfortable_kitchen_main05,
			"drawable://" + R.drawable.comfortable_kitchen_main06,
			"drawable://" + R.drawable.comfortable_kitchen_main07,
			"drawable://" + R.drawable.comfortable_kitchen_main08,
			"drawable://" + R.drawable.comfortable_kitchen_main09,
			"drawable://" + R.drawable.comfortable_kitchen_main10,
			"drawable://" + R.drawable.comfortable_kitchen_main11,
			"drawable://" + R.drawable.comfortable_kitchen_main12,
			"drawable://" + R.drawable.comfortable_kitchen_main13,
			"drawable://" + R.drawable.comfortable_kitchen_main14,
			"drawable://" + R.drawable.comfortable_kitchen_main15,
			"drawable://" + R.drawable.comfortable_kitchen_main16,
			"drawable://" + R.drawable.comfortable_kitchen_main17,
			"drawable://" + R.drawable.comfortable_kitchen_main18,
			"drawable://" + R.drawable.comfortable_kitchen_main19,
			"drawable://" + R.drawable.comfortable_kitchen_main20,
			"drawable://" + R.drawable.comfortable_naisou_main01,
			"drawable://" + R.drawable.comfortable_naisou_main02,
			"drawable://" + R.drawable.comfortable_naisou_main03,
			"drawable://" + R.drawable.comfortable_naisou_main04,
			"drawable://" + R.drawable.comfortable_naisou_main05,
			"drawable://" + R.drawable.comfortable_naisou_main06,
			"drawable://" + R.drawable.comfortable_naisou_main07,
			"drawable://" + R.drawable.comfortable_exterior_main01,
			"drawable://" + R.drawable.comfortable_exterior_main02,
			"drawable://" + R.drawable.comfortable_exterior_main03,
			"drawable://" + R.drawable.comfortable_exterior_main04,

	};

	public static final Integer[] IMAGES_THUMPS = new Integer[] {
			// Heavy images
			R.drawable.comfortable_bathroom_main01_thumb,
			R.drawable.comfortable_bathroom_main02_thumb,
			R.drawable.comfortable_bathroom_main03_thumb,
			R.drawable.comfortable_bathroom_main04_thumb,
			R.drawable.comfortable_bathroom_main05_thumb,
			R.drawable.comfortable_bathroom_main06_thumb,
			R.drawable.comfortable_bathroom_main07_thumb,
			R.drawable.comfortable_bathroom_main08_thumb,
			R.drawable.comfortable_bathroom_main09_thumb,
			R.drawable.comfortable_bathroom_main10_thumb,
			R.drawable.comfortable_bathroom_main11_thumb,
			R.drawable.comfortable_bathroom_main12_thumb,
			R.drawable.comfortable_bathroom_main13_thumb,
			R.drawable.comfortable_bathroom_main14_thumb,
			R.drawable.comfortable_bathroom_main15_thumb,
			R.drawable.comfortable_bathroom_main16_thumb,
			R.drawable.comfortable_bathroom_main17_thumb,
			R.drawable.comfortable_bathroom_main18_thumb,
			R.drawable.comfortable_bathroom_main19_thumb,
			R.drawable.comfortable_bathroom_main20_thumb,
			R.drawable.comfortable_bathroom_main21_thumb,
			R.drawable.comfortable_bathroom_main22_thumb,
			R.drawable.comfortable_bathroom_main23_thumb,
			R.drawable.comfortable_bathroom_main24_thumb,
			R.drawable.comfortable_bathroom_main25_thumb,
			R.drawable.comfortable_bathroom_main26_thumb,
			R.drawable.comfortable_bathroom_main27_thumb,
			R.drawable.comfortable_bathroom_main28_thumb,
			R.drawable.comfortable_bathroom_main29_thumb,
			R.drawable.comfortable_bathroom_main30_thumb,
			R.drawable.comfortable_bathroom_main31_thumb,
			R.drawable.comfortable_bathroom_main32_thumb,
			R.drawable.comfortable_bathroom_main33_thumb,
			R.drawable.comfortable_bathroom_main32_thumb,
			R.drawable.comfortable_bathroom_main33_thumb,
			R.drawable.comfortable_bathroom_main34_thumb,
			R.drawable.comfortable_bathroom_main35_thumb,
			R.drawable.comfortable_bathroom_main36_thumb,
			R.drawable.comfortable_bathroom_main37_thumb,
			R.drawable.comfortable_bathroom_main38_thumb,
			R.drawable.comfortable_bathroom_main39_thumb,
			R.drawable.comfortable_bathroom_main40_thumb,
			R.drawable.comfortable_kitchen_main01_thumb,
			R.drawable.comfortable_kitchen_main02_thumb,
			R.drawable.comfortable_kitchen_main03_thumb,
			R.drawable.comfortable_kitchen_main04_thumb,
			R.drawable.comfortable_kitchen_main05_thumb,
			R.drawable.comfortable_kitchen_main06_thumb,
			R.drawable.comfortable_kitchen_main07_thumb,
			R.drawable.comfortable_kitchen_main08_thumb,
			R.drawable.comfortable_kitchen_main09_thumb,
			R.drawable.comfortable_kitchen_main10_thumb,
			R.drawable.comfortable_kitchen_main11_thumb,
			R.drawable.comfortable_kitchen_main12_thumb,
			R.drawable.comfortable_kitchen_main13_thumb,
			R.drawable.comfortable_kitchen_main14_thumb,
			R.drawable.comfortable_kitchen_main15_thumb,
			R.drawable.comfortable_kitchen_main16_thumb,
			R.drawable.comfortable_kitchen_main17_thumb,
			R.drawable.comfortable_kitchen_main18_thumb,
			R.drawable.comfortable_kitchen_main19_thumb,
			R.drawable.comfortable_kitchen_main20_thumb,
			R.drawable.comfortable_naisou_main01_thumb,
			R.drawable.comfortable_naisou_main02_thumb,
			R.drawable.comfortable_naisou_main03_thumb,
			R.drawable.comfortable_naisou_main04_thumb,
			R.drawable.comfortable_naisou_main05_thumb,
			R.drawable.comfortable_naisou_main06_thumb,
			R.drawable.comfortable_naisou_main07_thumb,
			R.drawable.comfortable_exterior_main01_thumb,
			R.drawable.comfortable_exterior_main02_thumb,
			R.drawable.comfortable_exterior_main03_thumb,
			R.drawable.comfortable_exterior_main04_thumb, };

	private Constants() {
	}

	public static class Config {
		public static final boolean DEVELOPER_MODE = false;
	}

	public static class Extra {
		public static final String IMAGES = "com.nostra13.example.universalimageloader.IMAGES";
		public static final String IMAGE_POSITION = "com.nostra13.example.universalimageloader.IMAGE_POSITION";
	}

	public static final String POSITION_IMAGE = "POSITIONIMAGE";
}
